### PR TITLE
fix: Fixes CI lint check

### PR DESCRIPTION
**Pull request by gruyaume**
## Description

This PR fixes the currently broken lint check. The linting tool couldn't run because of the `whitespace` key that was defined twice in .golangci.yml.

Note: This PR does not fix the linting itself, those would come in a subsequent PR. The first step is to have a working CI.

### CODE REVIEW

**Comment by ghislainbourgeois** [comment]
Duplicate of #127

**Comment by dafATonf** [comment]
retest this please

**Comment by dafATonf** [comment]
test this please

**Review by thakurajayL — APPROVED** [review]

**Comment by thakurajayL** [comment]
Please rebase your code.

**Comment by gab-arrobo** [comment]
@dependabot rebase

**Comment by gab-arrobo** [comment]
@gruyaume, please address issue with `golangci-lint` GHA

**Comment by gruyaume** [comment]
> This PR does not fix the linting itself, those would come in a subsequent PR. The first step is to have a working CI.

@gab-arrobo as mentioned in the PR description, "This PR does not fix the linting itself, those would come in a subsequent PR. The first step is to have a working CI." All we do here is un break the file that describes lint checks.

**Comment by gab-arrobo** [comment]
> > This PR does not fix the linting itself, those would come in a subsequent PR. The first step is to have a working CI.
> 
> @gab-arrobo as mentioned in the PR description, "This PR does not fix the linting itself, those would come in a subsequent PR. The first step is to have a working CI." All we do here is un break the file that describes lint checks.

Got it. Thanks!

**Comment by gab-arrobo** [comment]
retest this please

**Pull request merged**
