### PR TITLE
chore: Use util v1.1.0

### PR DESCRIPTION
**Pull request by ghislainbourgeois**

### CODE REVIEW

**Comment by gab-arrobo** [comment]
@ghislainbourgeois can you please update the `metricfunc` and `nrf` repos first because the `amf` depends on these repos and they still use the now removed "tiny" repos (http2_util, logger_util). So, I can create new tags/release for these repos, and we use the latest version as part of this PR

**Comment by gab-arrobo** [comment]
@ghislainbourgeois, I just created tag/release `ngap v1.2.2`. Please accordingly update this PR with this change. Thanks!

**Comment by gab-arrobo** [comment]
@ghislainbourgeois, I just created tag/release `metricfunc v1.4.1`. Please accordingly update this PR with this change. Thanks!

**Comment by gab-arrobo** [comment]
@ghislainbourgeois now I am in the process of creating a new release/tag for the `NRF`. I will get back to you as soon as I finish testing my changes (<30 mins)

**Comment by gab-arrobo** [comment]
> @ghislainbourgeois now I am in the process of creating a new release/tag for the `NRF`. I will get back to you as soon as I finish testing my changes (<30 mins)

@ghislainbourgeois tag/release `nrf v1.4.1` was created

**Comment by ghislainbourgeois** [comment]
@gab-arrobo Once this is merged, we will need a tag of 1.4.2 for the AMF, this will be needed for gnbsim.

**Comment by gab-arrobo** [comment]
> @gab-arrobo Once this is merged, we will need a tag of 1.4.2 for the AMF, this will be needed for gnbsim.

Yes, I will try to do this by tonight.

**Review by gab-arrobo — APPROVED** [review]
+1

**Comment by gab-arrobo** [comment]
> @gab-arrobo Once this is merged, we will need a tag of 1.4.2 for the AMF, this will be needed for gnbsim.

@ghislainbourgeois, done, tag/release `v1.4.2` was created. Feel free to use it for the `gnbsim` update

**Pull request merged**
