### PR TITLE
 Parameterise webui url

### PR DESCRIPTION
**Pull request by gatici**
The Webui url is hardcoded in network function services. This PR makes Webui url changeable having an entry in the configuration file.

### CODE REVIEW

**Comment by gatici** [comment]
The change is tested and it passed the simulation successfully.

**Comment by gab-arrobo** [comment]
> The change is tested and it passed the simulation successfully.

Hi @gatici, have you tested the changes using/setting a different port number?

**Comment by gatici** [comment]
> > The change is tested and it passed the simulation successfully.
> 
> Hi @gatici, have you tested the changes using/setting a different port number?

Hello @gab-arrobo 

Port number 9876 is hard-coded in the webui. Unless we try the port in webui, it will fail if change to an another port number.

**Review by gab-arrobo — APPROVED** [review]
+1

**Pull request merged**
