### PR TITLE
Fix non-functional linting warnings

### PR DESCRIPTION
**Pull request by ghislainbourgeois**
Ran `golangci-lint run --fix` to automatically fix whitespace and import order warnings.

### CODE REVIEW

**Comment by dafATonf** [comment]
retest this please

**Comment by gab-arrobo** [comment]
retest this please

**Comment by gab-arrobo** [comment]
@ghislainbourgeois, I see several checks (components) are getting disabled in the golangci-linter. Is there a plan to re-enable them in future PRs?

**Comment by ghislainbourgeois** [comment]
Yes, the goal is to disable them now as they are failed ng, making the CI green. Afterwards, create 1 PR per linter to enable it again and fixing the issues at the same time.

This will make reviews a lot easier, and make sure we keep a green CI going forward.

**Review by gab-arrobo — APPROVED** [review]

**Pull request merged**
