### PR TITLE
ci: fix malformed configuration of golangci

### PR DESCRIPTION
**Pull request by isimluk**
Removing a duplicate block.

Addressing:
```
run golangci-lint
   Running [/home/runner/golangci-lint-1.54.2-linux-amd64/golangci-lint run --out-format=github-actions -v --config ./.golangci.yml] in [] ...
   level=error msg="Can't read config: can't read viper config: While parsing config: yaml: unmarshal errors:\n  line 217: mapping key \"whitespace\" already defined at line 209"
```

### CODE REVIEW

**Comment by isimluk** [comment]
@onf-cla-manager, how long does it take for the confirmation email to arrive?

**Comment by ajaythakurintel** [comment]
add to whitelist

**Review by ghislainbourgeois — APPROVED** [review]

**Comment by gab-arrobo** [comment]
test this please

**Comment by gab-arrobo** [comment]
test this please

**Comment by gab-arrobo** [comment]
@isimluk there are no changes in this PR. Should I close it?

**Comment by isimluk** [comment]
The changes disappeared from this PR after you merged the duplicate at #129.

**Pull request closed without merging**
